# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d452ffa37004d25901667e1cca7e6e83"
name = "Cialis"
handle = "cialis-1"
application_url = "https://clialis.project-progress.net"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shop-uk.cialistogether.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_customers,read_orders,write_content,write_customers,write_products"

[auth]
redirect_urls = [
  "https://clialis.project-progress.net/auth/callback",
  "https://clialis.project-progress.net/auth/shopify/callback",
  "https://clialis.project-progress.net/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
